# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Travis's native R Image (http://docs.travis-ci.com/user/languages/r/)
sudo:                false
language:            r
cache:               packages

os:
  - linux
  - osx

r_github_packages:
  - gagolews/stringi
